# rpc 配置
arc:
  # yaml 配置文件
  yaml: 
    modules: src/yaml/modules
    interface: src/yaml/interface
    struct: src/yaml/struct
  #  生成 client-server 的路径
  generate: 
    # 客户端生成rpc 接口文件需要的路径
    server: src/server
    # 服务端生成rpc 接口文件需要的路径
    client: src/rpc/client